# Generated by Django 3.0.2 on 2020-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='weight',
            field=models.FloatField(default=0, help_text='Peso del Contenedor'),
        ),
    ]
